---
## Q1: 행렬 곱 (Matrix Multiplication) 연산 <a name='q1'></a>

### 문제

크기가 `(3, 4)`인 모든 원소가 1인 텐서 `A`와, 크기가 `(4, 5)`인 랜덤 정규분포 텐서 `B`를 생성하세요.
그리고 두 텐서를 **행렬 곱(`tf.matmul`)**을 사용하여 곱한 결과 텐서 `C`를 만들고, `C`의 shape과 값을 출력하는 코드를 작성하세요.

**힌트:** 행렬 곱 조건: $A$의 **열 수** = $B$의 **행 수**


In [20]:
# 퀴즈 환경 설정
import tensorflow as tf
import numpy as np

tf.random.set_seed(42)
np.random.seed(42)

print(f"TensorFlow 버전: {tf.__version__}")
print("퀴즈 환경 준비 완료!")
print("각 문제를 풀기 전에 먼저 답을 예측해보세요.")

TensorFlow 버전: 2.16.2
퀴즈 환경 준비 완료!
각 문제를 풀기 전에 먼저 답을 예측해보세요.


---
## Q1: 행렬 곱 (Matrix Multiplication) 연산 <a name='q1'></a>

### 문제

크기가 `(3, 4)`인 모든 원소가 1인 텐서 `A`와, 크기가 `(4, 5)`인 랜덤 정규분포 텐서 `B`를 생성하세요.
그리고 두 텐서를 **행렬 곱(`tf.matmul`)**을 사용하여 곱한 결과 텐서 `C`를 만들고, `C`의 shape과 값을 출력하는 코드를 작성하세요.

**힌트:** 행렬 곱 조건: $A$의 **열 수** = $B$의 **행 수**


In [21]:
# TODO: 코드를 직접 작성해 보세요.
A = tf.ones([3,4])
B = tf.random.normal([4,5])

C = tf.matmul(A,B)

print(f"A shape : {A.numpy().shape}")
print(f"A : \n{A.numpy()}")
print(f"B shape : {B.numpy().shape}")
print(f"B : \n{B.numpy()}")
print(f"C shape : {C.numpy().shape}")
print(f"C : \n{C.numpy()}")

A shape : (3, 4)
A : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
B shape : (4, 5)
B : 
[[ 0.3274686  -0.8426257   0.3194336  -1.4075519  -2.3880599 ]
 [-1.0392478  -0.5573231   0.53970706  1.6994323   0.28893656]
 [-1.5066116  -0.26454768 -0.5972241  -1.9171132  -0.62044126]
 [ 0.8504024  -0.4060477  -3.025841    0.9058463   0.29855978]]
C shape : (3, 5)
C : 
[[-1.3679883 -2.0705442 -2.7639244 -0.7193866 -2.4210048]
 [-1.3679883 -2.0705442 -2.7639244 -0.7193866 -2.4210048]
 [-1.3679883 -2.0705442 -2.7639244 -0.7193866 -2.4210048]]


<details>
<summary>💡 정답 보기</summary>

```python
# ── Q1 풀이 ──────────────────────────────────────────────────
A = tf.ones([3, 4])   # (3행, 4열) 모든 원소 1
B = tf.random.normal([4, 5])   # (4행, 5열) 랜덤 정규분포

C = tf.matmul(A, B)

print("=" * 45)
print("Q1 풀이: 행렬 곱 C")
print("=" * 45)
print(f"A.shape = {A.shape}  →  (m=3, k=4)")
print(f"B.shape = {B.shape}  →  (k=4, n=5)")
print(f"-" * 45)
print(f"C = A @ B")
print(f"C.shape = {C.shape}  →  (m=3, n=5)")
print(f"\nC 값 일부 확인:\n{C[:2, :2].numpy()}")  # 값이 너무 많으므로 일부만 출력
```
</details>

---
## Q2: 브로드캐스팅 (Broadcasting) <a name='q2'></a>

### 문제

크기가 `(1, 4)`인 텐서 `X = [[1, 2, 3, 4]]`와 크기가 `(3, 1)`인 텐서 `Y = [[10], [20], [30]]`를 생성하세요.
`tf.add` 또는 `+` 연산자를 사용하여 두 텐서를 더한 결과 `Z`를 만들고 그 형태(shape)와 값을 확인하세요.

**브로드캐스팅 규칙 복습:**
1. 한쪽 차원이 **1**이면 다른 쪽 크기로 복사되어 확장
2. 낮은 차원은 왼쪽에 1차원을 추가하여 차원을 맞춤


In [22]:
# TODO: 코드를 직접 작성해 보세요.

X = tf.constant([[1,2,3,4]]) #행벡터
Y = tf.constant([[10],[20],[30]]) #열벡터

Z = tf.add(X,Y)
# [ [1,2,3,4]       [ [10]
#   [1,2,3,4]   +     [20]  
#   [1,2,3,4] ]       [30] ]


print(f"X shape : {X.numpy().shape}")
print(f"X : \n{X.numpy()}")
print(f"Y shape : {Y.numpy().shape}")
print(f"Y : \n{Y.numpy()}")
print(f"Z shape : {Z.numpy().shape}")
print(f"Z : \n{Z.numpy()}")

X shape : (1, 4)
X : 
[[1 2 3 4]]
Y shape : (3, 1)
Y : 
[[10]
 [20]
 [30]]
Z shape : (3, 4)
Z : 
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


<details>
<summary>💡 정답 보기</summary>

```python
# ── Q2 풀이 ──────────────────────────────────────────────────
X = tf.constant([[1, 2, 3, 4]], dtype=tf.float32)
Y = tf.constant([[10], [20], [30]], dtype=tf.float32)

Z = tf.add(X, Y)  # 또는 Z = X + Y

print("=" * 50)
print("Q2 풀이: 브로드캐스팅 결과 Shape 및 값")
print("=" * 50)
print(f"X.shape = {X.shape}")
print(f"Y.shape = {Y.shape}")
print(f"Z.shape = {Z.shape}")
print(f"\nZ의 값:\n{Z.numpy()}")
```
</details>

In [23]:
# Q2 심화: 다양한 브로드캐스팅 패턴

print("브로드캐스팅 심화 패턴:")

# (3,) + (2,3) → (2,3): 낮은 rank에 왼쪽 1 추가
v = tf.constant([1, 2, 3], dtype=tf.float32)          # (3,) → 사실상 (1,3)
m = tf.constant([[10,20,30],[40,50,60]], dtype=tf.float32)  # (2,3)
r = v + m
print(f"\n  (3,) + (2,3): {v.shape} + {m.shape} → {r.shape}")
print(f"  결과:\n{r.numpy()}")

# (3,1) + (1,4) → (3,4): 외적 덧셈
col = tf.constant([[1],[2],[3]], dtype=tf.float32)        # (3,1)
row = tf.constant([[10,20,30,40]], dtype=tf.float32)      # (1,4)
outer_sum = col + row
print(f"\n  (3,1) + (1,4): {col.shape} + {row.shape} → {outer_sum.shape}  (외적 덧셈)")
print(f"  결과:\n{outer_sum.numpy()}")

# 스칼라 브로드캐스팅
big_tensor = tf.zeros([3, 4, 5])
scalar = tf.constant(7.0)  # shape ()
r2 = big_tensor + scalar
print(f"\n  () + (3,4,5): {scalar.shape} + {big_tensor.shape} → {r2.shape}  (스칼라는 모든 원소에 적용)")

브로드캐스팅 심화 패턴:

  (3,) + (2,3): (3,) + (2, 3) → (2, 3)
  결과:
[[11. 22. 33.]
 [41. 52. 63.]]

  (3,1) + (1,4): (3, 1) + (1, 4) → (3, 4)  (외적 덧셈)
  결과:
[[11. 21. 31. 41.]
 [12. 22. 32. 42.]
 [13. 23. 33. 43.]]

  () + (3,4,5): () + (3, 4, 5) → (3, 4, 5)  (스칼라는 모든 원소에 적용)


---
## Q3: 텐서 차원 변경 (Transpose) <a name='q3'></a>

### 문제

0부터 23까지의 숫자를 가진 크기 `(2, 3, 4)`인 3D 텐서 `T`를 생성하세요.
(`tf.range`와 `tf.reshape` 활용)

이후, `tf.transpose` 연산을 사용하여 텐서의 축 순서를 기존 `(0, 1, 2)`에서 `(2, 0, 1)`로 변경한 `T_perm`을 만들고 그 shape을 출력하세요.


In [24]:
# TODO: 코드를 직접 작성해 보세요.

T_1d = tf.range(24)
T = tf.reshape(T_1d, [2,3,4])

T_perm = tf.transpose(T, perm=[2,0,1])

print(f"T shape : {T.shape}")
print(f"T_perm shape : {T_perm.shape}")
print(f"T_perm : \n{T_perm.numpy()}")

T shape : (2, 3, 4)
T_perm shape : (4, 2, 3)
T_perm : 
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


<details>
<summary>💡 정답 보기</summary>

```python
# ── Q3 풀이 ──────────────────────────────────────────────────
T_1d = tf.range(24)
T = tf.reshape(T_1d, [2, 3, 4])

T_perm = tf.transpose(T, perm=[2, 0, 1])

print("=" * 50)
print("Q3 풀이: Transpose 시 Shape 변화")
print("=" * 50)
print(f"원본 T.shape = {T.shape}")
print(f"변환 후 T_perm.shape = {T_perm.shape}")
print("\n[설명]")
print("새 축0 ← 기존 축2 (크기: 4)")
print("새 축1 ← 기존 축0 (크기: 2)")
print("새 축2 ← 기존 축1 (크기: 3)")
```
</details>

In [25]:
# Q3 심화: Transpose 원소 위치 변화 추적

# 작은 텐서로 원소 위치가 어떻게 바뀌는지 확인
small = tf.reshape(tf.range(12), [2, 3, 2])  # shape (2,3,2)
print(f"원본 shape: {small.shape}")
print(f"원본 값:")
print(small.numpy())

# 기본 transpose (역순: perm=[1,0,2] → 처음 두 축 교환)
t1 = tf.transpose(small, perm=[1, 0, 2])  # (3,2,2)
print(f"\ntranspose(perm=[1,0,2]) → shape: {t1.shape}")
print(t1.numpy())

print(f"\n[검증] 원본 small[0,1,0] = {small[0,1,0].numpy()}")
print(f"       변환 후  t1[1,0,0] = {t1[1,0,0].numpy()}")
print("       perm=[1,0,2] 이므로 축0↔축1 교환, 즉 [i,j,k] → [j,i,k]")

원본 shape: (2, 3, 2)
원본 값:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

transpose(perm=[1,0,2]) → shape: (3, 2, 2)
[[[ 0  1]
  [ 6  7]]

 [[ 2  3]
  [ 8  9]]

 [[ 4  5]
  [10 11]]]

[검증] 원본 small[0,1,0] = 2
       변환 후  t1[1,0,0] = 2
       perm=[1,0,2] 이므로 축0↔축1 교환, 즉 [i,j,k] → [j,i,k]


---
## Q4: GradientTape으로 미분 계산 <a name='q4'></a>

### 문제

`tf.GradientTape`은 딥러닝에서 역전파를 계산하는 데 필수적인 도구입니다. 이를 사용하여 다음 함수의 기울기를 구해보세요.

함수: $f(x) = 3x^2 + 2x + 1$

$x = 2.0$에서의 기울기(미분값)를 계산하고 출력하는 파이썬 코드를 작성하세요. (이론적 정답: $f'(2) = 14$)

**조건:**
- `x`는 `tf.Variable`로 선언해야 합니다.
- `tape.gradient()`를 사용해 `f(x)`의 `x`에 대한 미분값을 구하세요.


In [ ]:
# TODO: 코드를 직접 작성해 보세요.

x = tf.Variable(2.0)    #중요! integer가 들어가면 다른 의미가 되므로 '변수'라면 2.0처럼 소수의 형태로!!

with tf.GradientTape() as tape:
    f = 3 * x**2 + 2 * x + 1

df_dx = tape.gradient(f,x)


print(f"f'(2) = {df_dx.numpy()}")


f'(2) = 14.0


<details>
<summary>💡 정답 보기</summary>

```python
# ── Q4 풀이 ──────────────────────────────────────────────────
x = tf.Variable(2.0)

with tf.GradientTape() as tape:
    f = 3 * x**2 + 2 * x + 1

df_dx = tape.gradient(f, x)

print("=" * 50)
print("Q4 풀이: GradientTape 미분 계산")
print("=" * 50)
print(f"수학적 계산 결과: f'(2) = 6(2) + 2 = 14")
print(f"GradientTape 계산 결과: {df_dx.numpy()}")
```
</details>

In [36]:
# Q4 심화: 여러 x값에서 미분값 계산 및 시각화

# f(x) = 3x^2 + 2x + 1, f'(x) = 6x + 2

def compute_gradient(x_val):
    """주어진 x값에서 f(x)와 f'(x)를 반환"""
    x = tf.Variable(float(x_val))
    with tf.GradientTape() as tape:
        f = 3 * x**2 + 2 * x + 1
    df_dx = tape.gradient(f, x)
    return f.numpy(), df_dx.numpy()

print("f(x) = 3x² + 2x + 1  |  f'(x) = 6x + 2")
print("-" * 55)
print(f"{'x':>5} | {'f(x)':>10} | {'df_dx(x) TF':>12} | {'df_dx(x) 수식':>12}")
print("-" * 55)

for x_val in [-3, -2, -1, 0, 1, 2, 3]:
    f_val, grad_val = compute_gradient(x_val)
    theoretical = 6 * x_val + 2
    print(f"{x_val:>5} | {f_val:>10.1f} | {grad_val:>12.1f} | {theoretical:>12.1f}")

print("-" * 55)
print()
print("[해설] f'(x) = 6x + 2 = 0 → x = -1/3 ≈ -0.333 에서 최솟값")
f_min, _ = compute_gradient(-1/3)
print(f"       f(-1/3) ≈ {f_min:.4f}  (최솟값)")

f(x) = 3x² + 2x + 1  |  f'(x) = 6x + 2
-------------------------------------------------------
    x |       f(x) |  df_dx(x) TF |  df_dx(x) 수식
-------------------------------------------------------
   -3 |       22.0 |        -16.0 |        -16.0
   -2 |        9.0 |        -10.0 |        -10.0
   -1 |        2.0 |         -4.0 |         -4.0
    0 |        1.0 |          2.0 |          2.0
    1 |        6.0 |          8.0 |          8.0
    2 |       17.0 |         14.0 |         14.0
    3 |       34.0 |         20.0 |         20.0
-------------------------------------------------------

[해설] f'(x) = 6x + 2 = 0 → x = -1/3 ≈ -0.333 에서 최솟값
       f(-1/3) ≈ 0.6667  (최솟값)


In [ ]:
# Q4 응용: 경사하강법으로 f(x)의 최솟값 찾기
# GradientTape + 경사하강법 = 딥러닝 학습의 핵심 패턴

print("경사하강법으로 f(x) = 3x² + 2x + 1의 최솟값 찾기")
print(f"이론적 최솟값: x = -1/3 ≈ {-1/3:.4f}")
print()

x = tf.Variable(3.0)   # 임의의 시작점
lr = 0.05              # 학습률

print(f"{'에포크':>6} | {'x':>10} | {'f(x)':>10} | {'f\'(x)':>10}")
print("-" * 45)

for epoch in range(31):
    with tf.GradientTape() as tape:
        f = 3 * x**2 + 2 * x + 1
    grad = tape.gradient(f, x)
    x.assign_sub(lr * grad)   # x ← x - lr * f'(x)
    
    if epoch % 5 == 0:
        print(f"{epoch:>6} | {x.numpy():>10.6f} | {f.numpy():>10.6f} | {grad.numpy():>10.6f}")

print("-" * 45)
print(f"\n수렴된 x = {x.numpy():.6f}")
print(f"이론적 x = {-1/3:.6f}")
print(f"오차 = {abs(x.numpy() - (-1/3)):.8f}")

---
## Q5: tf.Variable 파라미터 제어 <a name='q5'></a>

### 문제

학습에 사용되는 가중치는 변할 수 있어야 합니다. 
`tf.Variable`을 사용하여 초기값이 `[1.0, 2.0, 3.0]`인 `W`라는 가중치 변수를 생성하세요.

이후, 모델이 한 번 학습했다고 가정하고 `W`의 값을 `assign_sub` 메서드를 사용하여 모두 `0.5`씩 빼서 업데이트하세요.
최종 업데이트된 `W`의 값을 출력하세요.


In [37]:
# TODO: 코드를 직접 작성해 보세요.

W = tf.Variable([1.0,2.0,3.0])
W.assign_sub([0.5,0.5,0.5])
print(f"{W.numpy()}")

[0.5 1.5 2.5]


<details>
<summary>💡 정답 보기</summary>

```python
# ── Q5 풀이 ──────────────────────────────────────────────────
W = tf.Variable([1.0, 2.0, 3.0])
print(f"초기 W = {W.numpy()}")

W.assign_sub([0.5, 0.5, 0.5])

print("=" * 50)
print("Q5 풀이: tf.Variable 업데이트")
print("=" * 50)
print(f"업데이트 된 W = {W.numpy()}")
```
</details>

In [ ]:
# Q5 심화: 학습 가능한 파라미터 직접 구현
# trainable=False로 특정 파라미터의 학습을 중지할 수 있음

print("학습 가능/불가능 파라미터 제어:")
print()

# 학습 가능 (기본)
w_trainable = tf.Variable([1.0, 2.0], name='trainable_weight', trainable=True)
# 학습 불가 (예: 고정된 임베딩, BatchNorm 통계)
w_frozen    = tf.Variable([3.0, 4.0], name='frozen_weight', trainable=False)

print(f"w_trainable.trainable = {w_trainable.trainable}")
print(f"w_frozen.trainable    = {w_frozen.trainable}")

x_input = tf.constant([1.0, 1.0])

with tf.GradientTape() as tape:
    # trainable=False인 Variable은 기본적으로 추적 안 됨
    output = tf.reduce_sum(w_trainable * x_input) + tf.reduce_sum(w_frozen * x_input)

grad_trainable = tape.gradient(output, w_trainable)
grad_frozen    = tape.gradient(output, w_frozen)   # 주의: 이미 tape 소비됨

print(f"\n그래디언트 결과:")
print(f"  ∂output/∂w_trainable = {grad_trainable.numpy() if grad_trainable is not None else 'None'}")
print(f"  ∂output/∂w_frozen    = {grad_frozen}  (trainable=False이므로 추적 안됨)")

print()

# Keras 레이어에서 trainable 제어
layer = tf.keras.layers.Dense(4, name='my_layer')
_ = layer(tf.ones([1, 3]))  # 레이어 빌드

print(f"Dense 레이어 파라미터:")
for var in layer.trainable_variables:
    print(f"  학습 가능 - {var.name}: shape={var.shape}")

# 레이어 동결
layer.trainable = False
print(f"\nlayer.trainable = False 후:")
print(f"  trainable_variables 수: {len(layer.trainable_variables)}  (0이 되어야 함)")
print(f"  non_trainable_variables 수: {len(layer.non_trainable_variables)}")

In [ ]:
# Q5 최종: tf.Variable의 주요 메서드 총정리

print("tf.Variable 주요 메서드 및 속성 총정리:")
print()

v = tf.Variable([[1.0, 2.0], [3.0, 4.0]], name='demo', trainable=True)

print(f"생성: v = tf.Variable([[1,2],[3,4]])")
print(f"  v.numpy()      = \n{v.numpy()}")
print(f"  v.name         = {v.name}")
print(f"  v.shape        = {v.shape}")
print(f"  v.dtype        = {v.dtype}")
print(f"  v.trainable    = {v.trainable}")
print()

print("값 수정 메서드:")
v.assign([[10., 20.], [30., 40.]])
print(f"  v.assign([[10,20],[30,40]]):")
print(f"    {v.numpy()}")

v.assign_add([[1., 1.], [1., 1.]])
print(f"  v.assign_add([[1,1],[1,1]]):")
print(f"    {v.numpy()}")

v.assign_sub([[1., 1.], [1., 1.]])
print(f"  v.assign_sub([[1,1],[1,1]]):")
print(f"    {v.numpy()}")

# 특정 인덱스 업데이트
v[0, 1].assign(99.)
print(f"  v[0,1].assign(99.):")
print(f"    {v.numpy()}")

---
## 종합 도전: XOR 신경망 순전파 밑바닥부터 구현 <a name='bonus'></a>

지금까지 배운 행렬 연산, 활성화 함수, 그리고 텐서를 모두 활용하여 간단한 XOR 해결용 뉴럴 네트워크의 **순전파(Forward Pass)**를 작성해 보세요.

**모델 구조:** Input(2차원) → Hidden Layer(4 유닛, ReLU 적용) → Output Layer(1 유닛, Sigmoid 적용)

아래 수식을 코드로 변환하세요 (Bias 포함):
- $H = \text{ReLU}(X \cdot W_1 + b_1)$
- $\hat{Y} = \sigma(H \cdot W_2 + b_2)$

랜덤하게 가중치($W_1$, $W_2$)와 편향($b_1$, $b_2$) 초기화 후, 한 배치의 XOR 입력 데이터(`[[0,0], [0,1], [1,0], [1,1]]`)에 대해 최종 예측값을 도출하는 형태면 충분합니다!


In [ ]:
# TODO: 코드를 직접 작성해 보세요.



<details>
<summary>💡 정답 보기</summary>

```python
# ── 종합 도전 풀이 ────────────────────────────────────────────
print("XOR 신경망 — 순전파 수동 구현")
print("=" * 50)

X = tf.constant([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])

# 랜덤 초기화
W1 = tf.Variable(tf.random.normal([2, 4]))
b1 = tf.Variable(tf.random.normal([4]))
W2 = tf.Variable(tf.random.normal([4, 1]))
b2 = tf.Variable(tf.random.normal([1]))

# Hidden Layer (ReLU)
H = tf.nn.relu(tf.matmul(X, W1) + b1)

# Output Layer (Sigmoid)
Y_hat = tf.nn.sigmoid(tf.matmul(H, W2) + b2)

print("입력 차원:", X.shape)
print("Hidden Layer 출력 차원:", H.shape)
print("\n[최종 예측 결과 (초기 가중치 상태)]")
print(Y_hat.numpy())
```
</details>

In [ ]:
# 순전파 함수 정의
def forward(X):
    """순전파: Input → ReLU Hidden → Sigmoid Output"""
    # 1층: h = ReLU(W1 @ X^T + b1)
    z1 = tf.matmul(X, W1) + b1        # (4,2)@(2,4) + (4,) = (4,4)
    h  = tf.nn.relu(z1)               # ReLU 활성화
    # 2층: y_hat = Sigmoid(W2 @ h^T + b2)
    z2 = tf.matmul(h, W2) + b2        # (4,4)@(4,1) + (1,) = (4,1)
    y_hat = tf.nn.sigmoid(z2)         # Sigmoid 활성화
    return y_hat

def bce_loss(y_true, y_pred):
    """이진 교차 엔트로피 손실"""
    eps = 1e-7
    y_pred = tf.clip_by_value(y_pred, eps, 1.0 - eps)  # 수치 안정성
    return -tf.reduce_mean(
        y_true * tf.math.log(y_pred) + (1 - y_true) * tf.math.log(1 - y_pred)
    )

# 학습 루프
optimizer = tf.keras.optimizers.Adam(learning_rate=0.05)

loss_history = []
print(f"{'에포크':>8} | {'BCE 손실':>12} | {'예측 (반올림)':>20}")
print("-" * 50)

for epoch in range(2001):
    with tf.GradientTape() as tape:
        y_pred = forward(X_xor)
        loss = bce_loss(Y_xor, y_pred)
    
    grads = tape.gradient(loss, params)
    optimizer.apply_gradients(zip(grads, params))
    
    loss_history.append(loss.numpy())
    
    if epoch % 500 == 0:
        preds = tf.round(y_pred).numpy().flatten()
        print(f"{epoch:>8} | {loss.numpy():>12.6f} | {preds}")

print("-" * 50)
print(f"\n학습 완료!")
print(f"최종 손실: {loss_history[-1]:.6f}")

In [ ]:
# TODO: 코드를 직접 작성해 보세요.



<details>
<summary>💡 정답 보기</summary>

```python
# 최종 예측 결과 확인
print("XOR 신경망 최종 예측 결과:")
print("-" * 50)
print(f"{'입력 x':>12} | {'실제 y':>8} | {'예측 확률':>12} | {'예측 (반올림)':>12} | {'정답':>6}")
print("-" * 50)

final_preds = forward(X_xor)
all_correct = True

for i in range(4):
    x_i = X_xor[i].numpy()
    y_true_i = Y_xor[i].numpy()[0]
    y_prob_i = final_preds[i].numpy()[0]
    y_pred_i = round(y_prob_i)
    correct = y_pred_i == y_true_i
    if not correct:
        all_correct = False
    status = "O" if correct else "X"
    print(f"  {str(x_i):>10} | {y_true_i:>8.0f} | {y_prob_i:>12.6f} | {y_pred_i:>12.0f} | {status:>6}")

print("-" * 50)
print(f"\n결과: {'모든 경우 정답!' if all_correct else 'XOR 아직 미완성 (더 학습 필요)'}")
print()
print("[요약] 이 XOR 구현에서 사용한 개념들:")
print("  - tf.Variable: 학습 가능한 파라미터 W1, b1, W2, b2")
print("  - tf.matmul:   행렬 곱으로 레이어 계산")
print("  - GradientTape: 자동 미분으로 역전파 계산")
print("  - Adam optimizer: 그래디언트 기반 파라미터 업데이트")
print("  - 브로드캐스팅: + b 편향 덧셈에 자동 적용")
```
</details>

---
## 전체 요약 및 핵심 공식 정리

### Q1~Q5 핵심 정리

| 문제 | 핵심 개념 | 결론 |
|------|-----------|------|
| **Q1** | 행렬 곱 shape | $(m, k) \times (k, n) \to (m, n)$ — 내부 차원 제거 |
| **Q2** | 브로드캐스팅 | 크기 1인 차원만 확장 가능. 1도 아니고 다르면 오류 |
| **Q3** | Transpose perm | `perm[i]` = 새 i번 축이 기존 몇 번 축인지 |
| **Q4** | GradientTape | `tape.gradient(y, x)` = $\frac{\partial y}{\partial x}$ |
| **Q5** | Variable vs Constant | 학습 파라미터는 반드시 `tf.Variable`로 선언 |

### 자주 쓰는 공식 모음

$$\text{행렬 곱: } C_{ij} = \sum_k A_{ik}B_{kj}$$

$$\text{편미분: } \frac{\partial f}{\partial x_i} \approx \frac{f(\ldots, x_i + \epsilon, \ldots) - f(\ldots, x_i, \ldots)}{\epsilon}$$

$$\text{연쇄 법칙: } \frac{\partial L}{\partial w} = \frac{\partial L}{\partial y} \cdot \frac{\partial y}{\partial w}$$

$$\text{경사하강법: } w \leftarrow w - \eta \frac{\partial L}{\partial w}$$

$$\text{MSE: } L = \frac{1}{n}\sum_{i=1}^{n}(y_i - \hat{y}_i)^2$$

$$\text{BCE: } L = -\frac{1}{n}\sum_i \left[ y_i \log \hat{y}_i + (1-y_i)\log(1-\hat{y}_i) \right]$$

---

### 다음 단계

Chapter 01의 기초를 완료했습니다. 다음 챕터들에서는:
- **Chapter 02:** Keras API로 신경망 구조화
- **Chapter 03:** 활성화 함수, 손실 함수, 옵티마이저 심화
- **Chapter 04:** CNN, RNN 등 특화 레이어

수고하셨습니다!